services:
  olist-api:
    build: ./
    container_name: olist_api
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION_STRING=postgresql://olist:olist123@olist_postgres_db:5432/olist_dw
      - API_TOKEN=olist123
    depends_on:
      - postgres
    networks:
      - olist_network

  postgres:
    build: ./postgres
    image: postgres:14.4-alpine
    container_name: olist_postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=olist
      - POSTGRES_PASSWORD=olist123
      - POSTGRES_DB=olist_dw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - olist_network

volumes:
  postgres_data:
    driver: "local"

networks:
  olist_network:
    driver: bridge
