version: '3'

services:
  olist-api:
    build: ./
    container_name: olist_api
    ports:
      - 8000:8000
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
    volumes:
      - ./:/api/
    depends_on:
      - postgres
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    networks:
      - olist_network
      
  postgres:
    image: postgres:14.4-alpine
    container_name: olist_postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/sql-scripts:/database/sql-scripts
      - ./database/sql-scripts/db_creation.sql:/docker-entrypoint-initdb.d/db_creation.sql
    networks:
      - olist_network
    
  pg4admin:
    image: dpage/pgadmin4
    container_name: olist_pg4admin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_DEFAULT_EMAIL=user@pgadmin.com
    volumes:
      - pg4admin_data:/var/lib/pgadmin
    networks:
      - olist_network

volumes:
  pg4admin_data:
    driver: "local"
  postgres_data:
    driver: "local"

networks:
  olist_network:
    driver: bridge
